# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-06-28T18:34:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Page(RootModel[int]):
    root: Annotated[
        int,
        Field(description='1-indexed page.', ge=-9007199254740991, le=9007199254740991),
    ]


class Type(Enum):
    pdf = 'pdf'
    image = 'image'


class ReferenceLocator1(BaseModel):
    """
    Spatial document locator (PDF/image).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    bbox: Annotated[list[Any] | None, Field(description='Fractional [x, y, w, h].')]
    page: Annotated[Page | None, Field(description='1-indexed page.')]
    type: Type


class Row(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='1-indexed source row (header = row 1).',
            ge=-9007199254740991,
            le=9007199254740991,
        ),
    ]


class ReferenceLocator2(BaseModel):
    """
    Tabular locator.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    row: Annotated[
        Row | None, Field(description='1-indexed source row (header = row 1).')
    ]
    type: Literal['tabular']


class ReferenceLocator3(BaseModel):
    """
    Audio time-range locator.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    endTime: Annotated[float | None, Field(description='Seconds.')]
    startTime: Annotated[float | None, Field(description='Seconds.')]
    type: Literal['audio']


class ReferenceLocator4(BaseModel):
    """
    Plain-text / markdown locator.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    position: Annotated[
        float | None, Field(description='Vertical position as a fraction (0..1).')
    ]
    type: Literal['text']


class ReferenceLocatorInput1(BaseModel):
    """
    Spatial document locator (PDF/image).
    """

    bbox: Annotated[list[Any] | None, Field(description='Fractional [x, y, w, h].')]
    page: Annotated[Page | None, Field(description='1-indexed page.')]
    type: Type


class ReferenceLocatorInput2(BaseModel):
    """
    Tabular locator.
    """

    row: Annotated[
        Row | None, Field(description='1-indexed source row (header = row 1).')
    ]
    type: Literal['tabular']


class ReferenceLocatorInput3(BaseModel):
    """
    Audio time-range locator.
    """

    endTime: Annotated[float | None, Field(description='Seconds.')]
    startTime: Annotated[float | None, Field(description='Seconds.')]
    type: Literal['audio']


class ReferenceLocatorInput4(BaseModel):
    """
    Plain-text / markdown locator.
    """

    position: Annotated[
        float | None, Field(description='Vertical position as a fraction (0..1).')
    ]
    type: Literal['text']


class CanonicalReference(BaseModel):
    """
    A single citation in the penpoint.ref/1 contract.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    confidence: Annotated[
        float | None,
        Field(description='Confidence in [0,1] that this is the right span, or null.'),
    ]
    id: Annotated[str, Field(description='Stable id for the cited span.')]
    locator: Annotated[
        ReferenceLocator1 | ReferenceLocator2 | ReferenceLocator3 | ReferenceLocator4,
        Field(
            description='Where a reference lives in the source, normalized per modality.'
        ),
    ]
    segment: Annotated[str, Field(description='The cited text content.')]


class CanonicalReferenceInput(BaseModel):
    """
    A single citation in the penpoint.ref/1 contract.
    """

    confidence: Annotated[
        float | None,
        Field(description='Confidence in [0,1] that this is the right span, or null.'),
    ]
    id: Annotated[str, Field(description='Stable id for the cited span.')]
    locator: Annotated[
        ReferenceLocatorInput1
        | ReferenceLocatorInput2
        | ReferenceLocatorInput3
        | ReferenceLocatorInput4,
        Field(
            description='Where a reference lives in the source, normalized per modality.'
        ),
    ]
    segment: Annotated[str, Field(description='The cited text content.')]
